all:
	python test_pgmagick_blob.py
	python test_pgmagick_color.py
	python test_pgmagick_image.py
	python test_pgmagick_geometry.py
	python test_pgmagick_montage.py
	python test_pgmagick_api.py

clean:
	rm *.png *.jpg
